name: Reusable Workflow 1

on:
  workflow_call:
    inputs:
      node:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: self-hosted
    steps:
      - name: Output the input value
        run: |
          echo "The node version to use is: ${{ inputs.node }}"          
